name: Deploy to k8s

on:
  push: 
    branches: 
    - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Deploy to k8s
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl get deployments -l app=eshop-web
        kubectl get pods -l app=eshop-web
        kubectl get services -l app=eshop-web